version: '3.8'

services:
  betterforward:
    image: ghcr.io/sidecloudgroup/betterforward:latest
    restart: unless-stopped
    environment:
      - TOKEN=8236572760:AAH9HiQ5aCFc_rRNygTGVF5GTF6H4i5iYiY
      - GROUP_ID=-1003517270710
      - LANGUAGE=zh_CN
      - TG_API=
      - WORKER=2
    volumes:
      - ./data:/app/data
